config/routes.rb
Rails.application.routes.draw do

  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { in: 1..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
  end
  
  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
    @tweet = Tweet.create(tweets_params)
    if @tweet.save
      redirect_to tweets_path, notice: "つぶやきました！"
    else
      render action: 'new'
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    
    if @tweet.update(tweets_params)
      redirect_to tweets_path, notice: "つぶやきを更新しました！"
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, notice: "つぶやきを削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
        confirm_tweets_path
      elsif action_name == 'edit'
        tweet_path
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tweets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1>Tweets</h1>
</header>

<%= yield %>

<footer>
  <p>Copyright &copy; 2016 tweets. All Rights Reserved.</p>
</footer>

</body>
</html>

app/views/top/index.html.erb
  <header>
    <ul>
      <li><a href="#">Achieve</a></li>
      <li><a href="#">トップページ</a></li>
      <li><a href="#">お問い合わせ</a></li>
      <li><a href="#">ブログ</a></li>
    </ul>
  </header>
  <section class="main-header">
    <img src="<%= asset_path "achieve.png" %>">
  </section>
  <section class="about">
    <h1>About Achieve</h1>
    <p>
       Achieveは、受講生のために作成された、教材用アプリです。<br>
       Achieveを作り終えることで、SecondTeamに参加するための力を身につけることができます。
    </p>
    <p>
       Acheiveを一言で表すと、タスク管理アプリです。<br>
       チームメンバーが、今どのようなタスクを行っているかリアルタイム
    </p>
  </section>
  <section class="function">
    <h2>Function</h2>
      <div class="function-images">
        <div class="function-image">
          <img src="<%= asset_path "key.png" %>">
          <p>ログイン機能</p>
        </div>
        <div class="function-image">
          <img src="<%= asset_path "mails.png" %>">
          <p>メール送信機能</p>
        </div>
        <div class="function-image">
          <img src="<%= asset_path "girls.png" %>">
          <p>友達つながり機能</p>
        </div>
        <div class="function-image">
          <img src="<%= asset_path "comment.png" %>">
          <p>コメント投稿機能</p>
        </div>
      </div>
  </section>
  <footer>
    運営会社タイムシフト株式会社</p><p>© 2015-2016 Copyright TimeShift Corp.
  </footer>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
  <div id="error_explanation">
      <p class="caution"><%= @tweet.errors.count %>件のエラーがあります</p>
      
      <ul class="mb15">
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  </div>
  <% end %>
  
  <%= f.label :ツイート内容 %>
  <%= f.text_field :content, class: 'form-control mb20' %>
  <%= f.submit 'ツイート', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ツイート一覧画面に戻る", tweets_path, class: 'btn btn-warning btn-block mt30' %>

app/views/tweets/confirm.html.erb
<h2 class="mb20">以下の内容で、ツイート</h2>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<%= form_for(@tweet) do |f| %>
  <%= f.hidden_field :content %>
  
  <p class="mb20"><%= @tweet.content %></p>
  <%= f.submit "ツイート", class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "戻る", name: 'back', class: 'btn btn-warning btn-block mt30' %>
<% end %>
  </div>
<!-- /.container --></div>

app/views/tweets/edit.html.erb
<h2 class="mb20">ツイートを編集する</h2>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
<!-- /.container --></div>

app/views/tweets/index.html.erb
<h2>ツイート一覧</h2>

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p class="caution"><%= notice %></p>

<%= link_to "ツイート", new_tweet_path, class: 'btn btn-primary btn-block mb20' %>

<% @tweets.each do |tweet| %>
  <div class="row mb20">
  <p><%= tweet.content %></p>
  <div class="btn_pos">
  <%= link_to "ツイートを編集する", edit_tweet_path(tweet.id), data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-default btn-sm btn-success' %>
  <%= link_to "ツイートを削除する", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %>
  <!-- /.btn_pos --></div>
  <!-- /.row --></div>
<% end %>

<%= link_to "ツイート", new_tweet_path, class: 'btn btn-primary btn-block' %>
<!-- /.warapper --></div>
<!-- /.container --></div>

<div id="page-top-btn" class="page-top-btn">
  <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/tweets/new.html.erb
<h2 class="mb20">ツイート</h2>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
<!-- /.container --></div>